use std::{
    convert::Infallible,
    num::{ParseFloatError, ParseIntError},
    str::ParseBoolError,
};

/// The error type when parsing XML document.
#[derive(Clone, Debug)]
pub enum ParseError {
    /// No `=` after an attribute name
    ExpectedEq,
    /// No quotes after an attribute name and `=`
    ExpectedQuote,
    /// Errors generated by quick_xml
    QuickXml(quick_xml::Error),
}

impl From<quick_xml::Error> for ParseError {
    fn from(value: quick_xml::Error) -> Self {
        Self::QuickXml(value)
    }
}

/// The error type when reading attribute value.
#[derive(PartialEq, Eq, Clone, Debug)]
pub enum AttrError {
    /// Attribute not found.
    NotFound(Vec<u8>),
    /// Attribute value is neither "true" nor "false".
    ParseBoolError(ParseBoolError),
    /// Attribute value is not a valid number.
    ParseFloatError(ParseFloatError),
    /// Attribute value is not a valid integer.
    ParseIntError(ParseIntError),
}

impl From<ParseBoolError> for AttrError {
    fn from(value: ParseBoolError) -> Self {
        Self::ParseBoolError(value)
    }
}

impl From<ParseFloatError> for AttrError {
    fn from(value: ParseFloatError) -> Self {
        Self::ParseFloatError(value)
    }
}

impl From<ParseIntError> for AttrError {
    fn from(value: ParseIntError) -> Self {
        Self::ParseIntError(value)
    }
}

impl From<Infallible> for AttrError {
    fn from(_: Infallible) -> Self {
        unreachable!()
    }
}
